# Generated by Django 2.0 on 2018-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
