# Generated by Django 2.0 on 2018-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.AddField(
            model_name='comment',
            name='entity',
            field=models.CharField(choices=[('review', 'Review'), ('report', 'Report')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='entity_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
