# Generated by Django 2.0 on 2018-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180307_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
