LIST_OF_NIGERIAN_UNIVERSITIES = [
    {
        'name': 'University of Lagos',
        'description': 'Founded in 1962, University of Lagos is a non-profit public higher education institution located in the urban setting of the metropolis of Lagos (population range of over 5,000,000 inhabitants). Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Lagos (UNILAG) is a very large (uniRank enrollment range: 35,000-39,999 students) coeducational higher education institution. University of Lagos (UNILAG) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 56 years old higher-education institution has a selective admission policy based on entrance examinations. International students are welcome to apply for enrollment. UNILAG also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.',
        'location': 'Yaba, Lagos',
        'logo_url': 'https://www.jobstoday.com.ng/wp-content/uploads/2016/06/1466408711-9013-unilag.png',
        'website': 'http://unilag.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Ahmadu Bello University',
        'description': "Established in 1962, Ahmadu Bello University is a non-profit public higher education institution located in the urban setting of the large city of Zaria (population range of 1,000,000-5,000,000 inhabitants), Kaduna. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Ahmadu Bello University (ABU) is a large (uniRank enrollment range: 25,000-29,999 students) coeducational higher education institution. Ahmadu Bello University (ABU) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 55 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 90-100% making this Nigerian higher education organization a least selective institution. International applicants are eligible to apply for enrollment. ABU also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.",
        'location': 'Zaria, Kaduna',
        'logo_url': 'https://dcs.abu.edu.ng/staff/sheidu-salami/images/abulogo.png',
        'website': 'http://abu.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Univerisy of Ibadan',
        'description': "Established in 1948, University of Ibadan is a non-profit public higher education institution located in the urban setting of the large city of Ibadan (population range of 1,000,000-5,000,000 inhabitants), Oyo. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Ibadan (UI) is a large (uniRank enrollment range: 20,000-24,999 students) coeducational higher education institution. University of Ibadan (UI) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 70 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 40-50% making this Nigerian higher education organization a averagely selective institution. International applicants are eligible to apply for enrollment. UI also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.",
        'location': 'Ibadan, Oyo',
        'logo_url': 'http://onemediastudios.net/wp-content/uploads/2015/09/UILOGO11.png',
        'website': 'http://ui.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'University of Nigeria',
        'description': 'Established in 1960, University of Nigeria is a non-profit public higher education institution located in the suburban setting of the small city of Nsukka (population range of 250,000-499,999 inhabitants), Enugu. This institution has also branch campuses in the following location(s): Enugu, Aba. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Nigeria (UNN) is a very large (uniRank enrollment range: 40,000-44,999 students) coeducational higher education institution. University of Nigeria (UNN) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 58 years old higher-education institution has a selective admission policy based on entrance examinations. The admission rate range is 40-50% making this Nigerian higher education organization a averagely selective institution. International applicants are eligible to apply for enrollment. UNN also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.',
        'location': 'Nsukka, Enugu',
        'logo_url': 'http://www.commonwealthofnations.org/wp-content/uploads/plogo/1346249482_university%20of%20nigeria%20logo.bmp',
        'website': 'http://www.unn.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'University of Ilorin',
        'description': 'Established in 1975, University of Ilorin is a non-profit public higher education institution located in the urban setting of the medium-sized city of Ilorin (population range of 500,000-1,000,000 inhabitants), Kwara. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Ilorin is a large (uniRank enrollment range: 25,000-29,999 students) coeducational higher education institution. University of Ilorin offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 43 years old higher-education institution has a selective admission policy based on entrance examinations. International applicants are eligible to apply for enrollment. University of Ilorin also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.',
        'location': 'Ilorin, Kwara',
        'logo_url': 'http://23069-presscdn.pagely.netdna-cdn.com/wp-content/uploads/2017/02/unilorin-logo-360x350.jpg',
        'website': 'http://www.unilorin.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Obafemi Awolowo University',
        'description': 'Established in 1962, Obafemi Awolowo University is a non-profit public higher education institution located in the suburban setting of the large town of Ile-Ife (population range of 50,000-249,999 inhabitants), Osun. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Obafemi Awolowo University (OAU) is a large (uniRank enrollment range: 25,000-29,999 students) coeducational higher education institution. Obafemi Awolowo University (OAU) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 56 years old higher-education institution has a selective admission policy based on entrance examinations. International applicants are eligible to apply for enrollment. OAU also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, as well as administrative services.',
        'location': 'Ile-Ife, Osun',
        'logo_url': 'http://www.best-masters.com/assets/img/logo_ecole/39.JPG',
        'website': 'http://www.oauife.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Federal University of Technology, Minna',
        'description': "Established in 1982, Federal University of Technology, Minna is a non-profit public higher education institution located in the suburban setting of the small city of Minna (population range of 250,000-499,999 inhabitants), Niger. This institution has also branch campuses in the following location(s): Bosso. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Federal University of Technology, Minna (FUT Minna) is a large (uniRank enrollment range: 15,000-19,999 students) coeducational higher education institution. Federal University of Technology, Minna (FUT Minna) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 36 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 80-90% making this Nigerian higher education organization a least selective institution. International applicants are eligible to apply for enrollment. FUT Minna also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Minna, Niger',
        'logo_url': 'https://www.futminna.edu.ng/images/FUTMINNA_LOGO.png',
        'website': 'http://www.futminna.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Covenant University',
        'description': 'Established in 2002, Covenant University is a non-profit private higher education institution located in the suburban setting of the large town of Ota (population range of 50,000-249,999 inhabitants), Ogun. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Covenant University (CU) is a medium-sized (uniRank enrollment range: 6,000-6,999 students) coeducational higher education institution formally affiliated with the Christian-Pentecostal religion. Covenant University (CU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 15 years old higher-education institution has a selective admission policy based on entrance examinations. The admission rate range is 40-50% making this Nigerian higher education organization a averagely selective institution. International applicants are eligible to apply for enrollment. CU also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.',
        'location': 'Ota, Ogun',
        'logo_url': 'http://covenantuniversity.edu.ng/var/cusite_admin/storage/images/media/images/cu-logo/9155-1-eng-GB/CU-Logo_imagelarge.png',
        'website': 'http://covenantuniversity.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Federal University of Technology, Akure',
        'description': 'Founded in 1981, Federal University of Technology, Akure is a non-profit public higher education institution located in the suburban setting of the small city of Akure (population range of 250,000-499,999 inhabitants), Ondo. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Federal University of Technology, Akure (FUTA) is a large (uniRank enrollment range: 20,000-24,999 students) coeducational higher education institution. Federal University of Technology, Akure (FUTA) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 37 years old higher-education institution has a selective admission policy based on entrance examinations. The admission rate range is 50-60% making this Nigerian higher education organization a averagely selective institution. International students are welcome to apply for enrollment. FUTA also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.',
        'location': 'Akure, Ondo',
        'logo_url': 'http://peakng.com/wp-content/uploads/2017/07/federal-university-of-technology-akure-futa-cut-off-mark-for-all-courses-jamb.png',
        'website': 'http://www.futa.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'University of Port Harcourt',
        'description': "Established in 1975, University of Port Harcourt is a non-profit public higher education institution located in the suburban setting of the large city of Port Harcourt (population range of 1,000,000-5,000,000 inhabitants), Rivers. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Port Harcourt (Uniport) is a very large (uniRank enrollment range: 35,000-39,999 students) coeducational higher education institution. University of Port Harcourt (Uniport) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 43 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 0-10% making this Nigerian higher education organization a most selective institution. International applicants are eligible to apply for enrollment. Uniport also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.",
        'location': 'Port Harcourt, Rivers',
        'logo_url': 'http://www.postutme.org.ng/wp-content/uploads/2015/06/Uniport.jpg',
        'website': 'http://www.uniport.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Landmark University',
        'description': "Established in 2011, Landmark University is a non-profit private higher education institution located in Omu-Aran, Kwara. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Landmark University (LMU) is a small (uniRank enrollment range: 2,000-2,999 students) coeducational higher education institution formally affiliated with the Christian-Pentecostal religion. Landmark University (LMU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 6 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 60-70% making this Nigerian higher education organization a somewhat selective institution. International applicants are eligible to apply for enrollment. LMU also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, as well as administrative services.",
        'location': 'Omu-Aran, Kwara',
        'logo_url': 'http://talkopportunity.com/wp-content/uploads/2017/12/LMU.png',
        'website': 'http://lmu.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'University of Benin',
        'description': 'Founded in 1970, University of Benin is a non-profit public higher education institution located in the large city of Benin City (population range of 1,000,000-5,000,000 inhabitants), Edo. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Benin (UNIBEN) is a very large (uniRank enrollment range: 40,000-44,999 students) coeducational higher education institution. University of Benin (UNIBEN) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 48 years old higher-education institution has a selective admission policy based on entrance examinations. The admission rate range is 90-100% making this Nigerian higher education organization a least selective institution. UNIBEN also provides several academic and non-academic facilities and services to students including a library, as well as administrative services.',
        'location': 'Benin City, Edo',
        'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Uniben.png',
        'website': 'http://www.uniben.edu/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Federal University of Agriculture, Abeokuta',
        'description': 'Established in 1988, Federal University of Agriculture, Abeokuta is a non-profit public higher education institution located in the urban setting of the medium-sized city of Abeokuta (population range of 500,000-1,000,000 inhabitants), Ogun. This institution has also branch campuses in the following location(s): Cenhurd. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Federal University of Agriculture, Abeokuta (FUNAAB) is a large (uniRank enrollment range: 10,000-14,999 students) coeducational higher education institution. Federal University of Agriculture, Abeokuta (FUNAAB) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 30 years old higher-education institution has a selective admission policy based on entrance examinations. The admission rate range is 40-50% making this Nigerian higher education organization a averagely selective institution. International applicants are eligible to apply for enrollment. FUNAAB also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.',
        'location': 'Abeokuta, Ogun',
        'logo_url': 'https://pbs.twimg.com/profile_images/1110153942/UNAAB_LOGO.jpg',
        'website': 'http://www.unaab.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Federal University, Oye-Ekiti',
        'description': "Established in 2011, Federal University, Oye-Ekiti is a non-profit public higher education institution located in the rural setting of the medium-sized town of Oye-Ekiti (population range of 10,000-49,999 inhabitants), Ekiti. This institution has also branch campuses in the following location(s): Ikole. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Federal University, Oye-Ekiti (FUOYE) is a medium-sized (uniRank enrollment range: 6,000-6,999 students) coeducational higher education institution. Federal University, Oye-Ekiti (FUOYE) offers courses and programs leading to officially recognized higher education degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 7 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 60-70% making this Nigerian higher education organization a somewhat selective institution. International applicants are eligible to apply for enrollment. FUOYE also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Oye-Ekiti, Ekiti',
        'logo_url': 'http://repository.fuoye.edu.ng/retrieve/88',
        'website': 'http://fuoye.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Lagos State University',
        'description': 'Established in 1983, Lagos State University is a non-profit public higher education institution located in Ojo, Lagos. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Lagos State University (LASU) is a large (uniRank enrollment range: 15,000-19,999 students) coeducational higher education institution. Lagos State University (LASU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 35 years old higher-education institution has a selective admission policy based on entrance examinations. LASU also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, as well as administrative services.',
        'location': 'Ojo, Lagos',
        'logo_url': 'http://lasu.edu.ng/iive/print_forms/Images_pg/LASULOGO.gif',
        'website': 'http://www.lasu.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Bayero University Kano',
        'description': 'Established in 1975, Bayero University Kano is a non-profit public higher education institution located in the large city of Kano (population range of 1,000,000-5,000,000 inhabitants). Officially accredited and/or recognized by the National Universities Commission, Nigeria, Bayero University Kano (BUK) is a medium-sized (uniRank enrollment range: 7,000-7,999 students) coeducational higher education institution. Bayero University Kano (BUK) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 43 years old higher-education institution has a selective admission policy based on entrance examinations. BUK also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, as well as administrative services.',
        'location': 'Kano, Kano',
        'logo_url': 'https://i0.wp.com/www.campusportalng.com/wp-content/uploads/2012/11/bayero-university-kano-buk-logo.jpg?resize=240%2C274&ssl=1',
        'website': 'http://www.buk.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'American University of Nigeria',
        'description': "Founded in 2004, American University of Nigeria is a non-profit private higher education institution located in the rural setting of the large town of Yola (population range of 50,000-249,999 inhabitants), Adamawa. Officially accredited and/or recognized by the National Universities Commission, Nigeria, American University of Nigeria (AUN) is a very small (uniRank enrollment range: 1,000-1,999 students) coeducational higher education institution. American University of Nigeria (AUN) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 14 years old higher-education institution has a selective admission policy based on students' past academic record and grades. The admission rate range is 30-40% making this Nigerian higher education organization a very selective institution. International students are welcome to apply for enrollment. AUN also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.",
        'location': 'Yola, Adamawa',
        'logo_url': 'https://media.premiumtimesng.com/wp-content/files/banners/AUN_Logo_1_894809455.jpg',
        'website': 'http://www.aun.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'University of Jos',
        'description': "Founded in 1975, University of Jos is a non-profit public higher education institution located in the urban setting of the large city of Jos (population range of 1,000,000-5,000,000 inhabitants), Plateau. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Jos (UNIJOS) is a large (uniRank enrollment range: 15,000-19,999 students) coeducational higher education institution. University of Jos (UNIJOS) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 43 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 0-10% making this Nigerian higher education organization a most selective institution. International students are welcome to apply for enrollment. UNIJOS also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Jos, Plateau',
        'logo_url': 'http://prepclass.com.ng/blog/wp-content/uploads/2013/07/University_of_Jos_logo1.jpg',
        'website': 'http://www.unijos.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Rivers State University of Science and Technology',
        'description': 'Founded in 1980, Rivers State University of Science and Technology is a non-profit public higher education institution located in the urban setting of the large city of Port Harcourt (population range of 1,000,000-5,000,000 inhabitants), Rivers. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Rivers State University of Science and Technology (RSUST) is a large (uniRank enrollment range: 10,000-14,999 students) coeducational higher education institution. Rivers State University of Science and Technology (RSUST) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 38 years old higher-education institution has a selective admission policy based on entrance examinations. The admission rate range is 0-10% making this Nigerian higher education organization a most selective institution. RSUST also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.',
        'location': 'Port Harcourt, Rivers',
        'logo_url': 'https://2.bp.blogspot.com/-N18EXzKx89M/WadKsRKeQ7I/AAAAAAAAAiE/IqEG4mCMU9s3mVfUH2TjXjg315nwiunBgCLcBGAs/s400/RSU.infohubonline.com.ng.jpg',
        'website': 'http://www.rsu.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Federal University of Technology, Owerri',
        'description': 'Founded in 1980, Federal University of Technology, Owerri is a non-profit public higher education institution located in the urban setting of the large town of Owerri (population range of 50,000-249,999 inhabitants), Imo. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Federal University of Technology, Owerri (FUTO) is a coeducational higher education institution. Federal University of Technology, Owerri (FUTO) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. FUTO also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, as well as administrative services.',
        'location': 'Owerri, Imo',
        'logo_url': 'https://4.bp.blogspot.com/-WTwlHyvlBLc/WeMqupPZTrI/AAAAAAAABoA/3kdhddcslfsAR0dNU3_ZzBWAc3GsXO9BACLcBGAs/s1600/Federal-University-of-Technology-Owerri-logo.jpg',
        'website': 'http://futo.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'University of Uyo',
        'description': 'Founded in 1991, University of Uyo is a non-profit public higher education institution located in the large town of Uyo (population range of 50,000-249,999 inhabitants), Akwa Ibom. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Uyo is a coeducational higher education institution. University of Uyo offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. University of Uyo also provides several academic and non-academic facilities and services to students including a library, online courses and distance learning opportunities, as well as administrative services.',
        'location': 'Uyo, Akwa Ibom',
        'logo_url': 'http://yscholars.com/wp-content/uploads/2016/06/University-of-Uyo-UNIUYO.jpg',
        'website': 'http://www.uniuyo.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Nnamdi Azikiwe University',
        'description': "Established in 1991, Nnamdi Azikiwe University is a non-profit public higher education institution located in the suburban setting of the small city of Awka (population range of 250,000-499,999 inhabitants), Anambra. This institution has also branch campuses in the following location(s): Nnewi. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Nnamdi Azikiwe University (NAU) is a very large (uniRank enrollment range: 30,000-34,999 students) coeducational higher education institution. Nnamdi Azikiwe University (NAU) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 27 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 10-20% making this Nigerian higher education organization a most selective institution. International applicants are eligible to apply for enrollment. NAU also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Akwa, Anambra',
        'logo_url': 'http://yscholars.com/wp-content/uploads/2015/08/unizik-logo.jpg',
        'website': 'http://unizik.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Usmanu Danfodio University',
        'description': 'Founded in 1975, Usmanu Danfodio University is a non-profit public higher education institution located in the urban setting of the small city of Sokoto (population range of 250,000-499,999 inhabitants). Officially accredited and/or recognized by the National Universities Commission, Nigeria, Usmanu Danfodio University (UDU) is a coeducational higher education institution. Usmanu Danfodio University (UDU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 43 years old higher-education institution has a selective admission policy based on entrance examinations. UDU also provides several academic and non-academic facilities and services to students including a library, online courses and distance learning opportunities, as well as administrative services.',
        'location': 'Sokoto, Sokoto',
        'logo_url': "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=&url=http%3A%2F%2Fpunchng.s3-eu-west-1.amazonaws.com%2Fwp-content%2Fuploads%2F2017%2F06%2F24140244%2FUsman-Dan-Fodio-University.jpg&psig=AOvVaw1jBoPqTJRLVjEQCTUYHufW&ust=1516807950644641",
        'website': 'http://www.udusok.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Michael Okpara University of Agriculture',
        'description': 'Founded in 1992, Michael Okpara University of Agriculture is a non-profit public higher education institution located in the large town of Umuahia (population range of 50,000-249,999 inhabitants), Abia. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Michael Okpara University of Agriculture (MOUAU) is a large (uniRank enrollment range: 10,000-14,999 students) coeducational higher education institution. Michael Okpara University of Agriculture (MOUAU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 26 years old higher-education institution has a selective admission policy based on entrance examinations. MOUAU also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, as well as administrative services.',
        'location': 'Umuahia, Abia',
        'logo_url': 'https://mouau.edu.ng/sites/default/files/inline-images/MOUAU-Logo_2.png',
        'website': 'http://mouauportal.edu.ng/',
        'rank': None,
        'rating': None,
    },
     {
        'name': 'Ladoke Akintola University of Technology',
        'description': "Founded in 1990, Ladoke Akintola University of Technology is a non-profit public higher education institution located in the rural setting of the medium-sized city of Ogbomoso (population range of 500,000-1,000,000 inhabitants), Oyo. This institution has also branch campuses in the following location(s): Osogbo. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Ladoke Akintola University of Technology (LAUTECH) is a large (uniRank enrollment range: 20,000-24,999 students) coeducational higher education institution. Ladoke Akintola University of Technology (LAUTECH) offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 27 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 10-20% making this Nigerian higher education organization a most selective institution. International students are welcome to apply for enrollment. LAUTECH also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Ogbomoso. Oyo',
        'logo_url': 'http://esther.ng/wp-content/uploads/2016/08/Ladoke-Akintola-University-of-Technology-lautech-esther.ng_.jpg',
        'website': 'http://www.lautech.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Babcock University',
        'description': "Established in 1999, Babcock University is a non-profit private higher education institution located in the suburban setting of the medium-sized town of Ilishan-Remo (population range of 10,000-49,999 inhabitants), Ogun. This institution has also branch campuses in the following location(s): Iperu-Remo. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Babcock University (BU) is a small (uniRank enrollment range: 5,000-5,999 students) coeducational higher education institution formally affiliated with the Christian-Adventist religion. Babcock University (BU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 18 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 10-20% making this Nigerian higher education organization a most selective institution. International applicants are eligible to apply for enrollment. BU also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Ilishan-Remo, Ogun',
        'logo_url': 'https://i0.wp.com/campusheathq.com/wp-content/uploads/2013/05/Babcock-Uni-Logo.jpg',
        'website': 'http://www.babcock.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Adekunle Ajasin University',
        'description': "Founded in 1982, Adekunle Ajasin University is a non-profit public higher education institution located in the suburban setting of the small city of Akungba Akoko (population range of 250,000-499,999 inhabitants), Ondo. This institution has also branch campuses in the following location(s): Ikare Akoko. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Adekunle Ajasin University (AAUA) is a large (uniRank enrollment range: 10,000-14,999 students) coeducational higher education institution. Adekunle Ajasin University (AAUA) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 36 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 40-50% making this Nigerian higher education organization a averagely selective institution. International students are welcome to apply for enrollment. AAUA also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, study abroad and exchange programs, as well as administrative services.",
        'location': 'Akungba Akoko, Ondo',
        'logo_url': 'https://static.pulse.ng/img/incoming/origs3453304/0050487601-w980-h640/AAUA-logo.jpg',
        'website': 'http://aaua.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'University of Abuja',
        'description': "Established in 1988, University of Abuja is a non-profit public higher education institution located in the suburban setting of the large town of Abuja (population range of 50,000-249,999 inhabitants), Federal Capital Territory. Officially accredited and/or recognized by the National Universities Commission, Nigeria, University of Abuja is a coeducational higher education institution. University of Abuja offers courses and programs leading to officially recognized higher education degrees such as pre-bachelor degrees (i.e. certificates, diplomas, associate or foundation degrees), bachelor degrees, master degrees, doctorate degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 30 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. International applicants are eligible to apply for enrollment. University of Abuja also provides several academic and non-academic facilities and services to students including a library, as well as administrative services.",
        'location': 'Abuja, FCT',
        'logo_url': 'https://web.uniabuja.edu.ng/wp-content/uploads/2017/05/cropped-abuja-logo-1.jpg',
        'website': 'http://www.uniabuja.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Afe Babalola University',
        'description': "Established in 2009, Afe Babalola University is a non-profit private higher education institution located in the urban setting of the small city of Ado-Ekiti (population range of 250,000-499,999 inhabitants), Ekiti. Officially accredited and/or recognized by the National Universities Commission, Nigeria, Afe Babalola University (ABUAD) is a small (uniRank enrollment range: 5,000-5,999 students) coeducational higher education institution. Afe Babalola University (ABUAD) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees, master degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. This 8 years old higher-education institution has a selective admission policy based on entrance examinations and students' past academic record and grades. The admission rate range is 90-100% making this Nigerian higher education organization a least selective institution. International applicants are eligible to apply for enrollment. ABUAD also provides several academic and non-academic facilities and services to students including a library, housing, sport facilities and/or activities, financial aids and/or scholarships, study abroad and exchange programs, as well as administrative services.",
        'location': 'Ado-Ekiti, Ekiti',
        'logo_url': 'https://portal.abuad.edu.ng/admin/images/Logo.png',
        'website': 'http://www.abuad.edu.ng/',
        'rank': None,
        'rating': None,
    },
    {
        'name': 'Abubakar Tafawa Balewa University',
        'description': 'Founded in 1988, Abubakar Tafawa Balewa University is a non-profit public higher education institution located in the urban setting of the small city of Bauchi (population range of 250,000-499,999 inhabitants). Officially accredited and/or recognized by the National Universities Commission, Nigeria, Abubakar Tafawa Balewa University (ATBU) is a coeducational higher education institution. Abubakar Tafawa Balewa University (ATBU) offers courses and programs leading to officially recognized higher education degrees such as bachelor degrees in several areas of study. See the uniRank degree levels and areas of study matrix below for further details. ATBU also provides several academic and non-academic facilities and services to students including a library, sport facilities and/or activities, as well as administrative services.',
        'location': 'Bauchi, Bauchi',
        'logo_url': 'https://students.com.ng/wp-content/uploads/2014/03/atbu-logo.jpg',
        'website': 'http://www.atbu.edu.ng/',
        'rank': None,
        'rating': None,
    },
]